[build]
command = "bun run build --preset netlify"
publish = ".netlify/functions-internal"
functions = ".netlify/functions-internal"

[functions]
node_bundler = "esbuild"

[[edge_functions]]
function = "ssr"
path = "/*"
