[build]
command = "bun run build --preset netlify"
publish = "dist/_build"
functions = "dist/server"

[functions]
node_bundler = "esbuild"

[dev]
framework = "#static"
command = "bun dev"   # or npm run dev
targetPort = 3000
port = 3000

[[edge_functions]]
function = "ssr"
path = "/*"
